##### generating .bib file to cite packages #####
library(grateful)
### list of p_loads from all of my r scripts so they're loaded in the "session"
p_load(here, tidyverse, daymetr, snotelr, rstac, rsi, ncdf4, parallel, svMisc, sf, terra)
p_load(here, tidyverse, sf, terra, parallel, tidyterra)
p_load(here, tidyverse, sf, terra, parallel)
p_load(here, tidyverse, sf, terra, tidyterra)
p_load(here, tidyverse, terra, sf, tidyterra, RColorBrewer, viridis, ggthemes, ggspatial, basemaps)
p_load(here, tidyverse, sf, terra, sfext, parallel, data.table, mcprogress, dtplyr, gt, gtExtras, RColorBrewer)
p_load(tidyverse, here, sf, terra, tidyterra, sabre, data.table, bespatial, parallel, mcprogress)
p_load(tidyverse, here, sf, terra, sfext, parallel, data.table, mcprogress, dtplyr, gt, gtExtras, RColorBrewer)
p_load(here, tidyverse, sf, terra, gt, gtExtras)
p_load(here, tidyverse, daymetr, ncdf4, parallel, svMisc, sf, terra)
p_load(here, tidyverse, parallel, sf, terra)
p_load(here, tidyverse, sf, terra, parallel)
p_load(here, tidyverse, sf, terra, ncdf4, parallel, tidyterra)
p_load(here, tidyverse, sf, terra, ncdf4, parallel, daymetr, tidyterra)
p_load(here, tidyverse, terra, sf, daymetr)
p_load(here, tidyverse, terra, sf)
p_load(here, tidyverse, sf, terra, parallel, rsample, mcprogress)
p_load(here, tidyverse, randomForest, sf, terra, sfext, rsample, caret, parallel, grateful, ModelMetrics, Metrics, mcprogress)
p_load(here, tidyverse, randomForest, sf, terra, sfext, rsample, caret, parallel, grateful, ModelMetrics, Metrics, mcprogress)
p_load(here, tidyverse, randomForest, sf, terra, sfext, rsample, caret, parallel, grateful, ModelMetrics, Metrics, mcprogress)
p_load(here, tidyverse, randomForest, gt, gtExtras, sf, terra, sfext, rsample, caret, parallel, grateful, ModelMetrics, Metrics)
p_load(here, caret, randomForest, tidyverse, terra, sf, tidyterra, RColorBrewer, viridis, ModelMetrics, ggthemes, ggspatial, mcprogress, data.table, parallel)
p_load(here, tidyverse, data.table, shapviz, fastshap, ggthemes)
p_load(here, tidyverse, gt, gtExtras)
p_load(here, tidyverse, randomForest, sf, terra, sfext, caret, parallel, grateful, treeshap, data.table, mcprogress)
p_load(tidyverse, randomForest, sf, terra, sfext, caret, parallel, data.table, rsample, mcprogress, fastshap, shapviz)
p_load(tidyverse, randomForest, sf, terra, sfext, caret, parallel, data.table, rsample, mcprogress, fastshap, shapviz)
library(spatialRF)
cite_packages(output = "file", out.dir = here("Outputs", "RCitations"), pkgs = "Session", bib.file = "RPackageBibtex")
